package game;

import java.util.Random;
import java.util.Scanner;

public class Helper implements IHelper {
    public String programName = "CARD DUELS";
    public static String[] monsterNames = {
            "Mistwings",
            "Tombbeast",
            "Murkhood",
            "The Hollow Wraith",
            "The Acidic Hag",
            "The Infamous Eyes",
            "The Stalking Frost Spider",
            "The Grisly Killer Monkey",
            "The Greater Storm Serpent",
            "The Disfigured Entity"
        };
        
        public Scanner console = new Scanner(System.in);

        /**
         * This method will facilitate easier System.out.
         * @param o - Object.
         */
        public static void out(Object o){
    	    System.out.println(o.toString());
        }

        /**
         * This method will return the games instructions when called. 
         * @return a String.
         */
        public String instruction() {
            return 
                    "*********************************************" + "\n" +
                    "The Goal to play is to first choose your player" + "\n"
                  + "Then 5 cards will be generated by different sets of Monster, Trap, or Magician Card" + "\n"
                  + "Pick a battle with the player that your against with and draw a card to play" + "\n" 
                  + "The player with the most amount of cards win! ...." + "\n"
                  + "*********************************************"
                  ;
        }

        public String generate(String[] n) {
            Random nameR = new Random();
            int r = nameR.nextInt(n.length);
            return n[r];
        }
        
        public int generateNum() {
            Random nums = new Random();
            int n = nums.nextInt(100);
            return n += 1;
        }
}
